  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: puppetmaster
      POSTGRES_PASSWORD: passwordio
      POSTGRES_DB: puppetmaster
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db:db